# This workflow executes several linters on changed files based on languages used in your code base whenever
# you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/github/super-linter
name: Compile Code Base

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  compile-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Run cmake
        run: cd build; cmake ..
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

